# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jacob/Desktop/OO-Types

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jacob/Desktop/OO-Types

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacob/Desktop/OO-Types/CMakeFiles /home/jacob/Desktop/OO-Types/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacob/Desktop/OO-Types/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named SRCLIB

# Build rule for target.
SRCLIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SRCLIB
.PHONY : SRCLIB

# fast build rule for target.
SRCLIB/fast:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/build
.PHONY : SRCLIB/fast

#=============================================================================
# Target rules for targets named delete

# Build rule for target.
delete: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 delete
.PHONY : delete

# fast build rule for target.
delete/fast:
	$(MAKE) -f CMakeFiles/delete.dir/build.make CMakeFiles/delete.dir/build
.PHONY : delete/fast

#=============================================================================
# Target rules for targets named document

# Build rule for target.
document: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 document
.PHONY : document

# fast build rule for target.
document/fast:
	$(MAKE) -f CMakeFiles/document.dir/build.make CMakeFiles/document.dir/build
.PHONY : document/fast

#=============================================================================
# Target rules for targets named cmake

# Build rule for target.
cmake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmake
.PHONY : cmake

# fast build rule for target.
cmake/fast:
	$(MAKE) -f CMakeFiles/cmake.dir/build.make CMakeFiles/cmake.dir/build
.PHONY : cmake/fast

#=============================================================================
# Target rules for targets named IntegerTest

# Build rule for target.
IntegerTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IntegerTest
.PHONY : IntegerTest

# fast build rule for target.
IntegerTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/IntegerTest.dir/build.make bin/test/CMakeFiles/IntegerTest.dir/build
.PHONY : IntegerTest/fast

#=============================================================================
# Target rules for targets named FloatTest

# Build rule for target.
FloatTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FloatTest
.PHONY : FloatTest

# fast build rule for target.
FloatTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/FloatTest.dir/build.make bin/test/CMakeFiles/FloatTest.dir/build
.PHONY : FloatTest/fast

#=============================================================================
# Target rules for targets named UnsignedIntegerTest

# Build rule for target.
UnsignedIntegerTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UnsignedIntegerTest
.PHONY : UnsignedIntegerTest

# fast build rule for target.
UnsignedIntegerTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/UnsignedIntegerTest.dir/build.make bin/test/CMakeFiles/UnsignedIntegerTest.dir/build
.PHONY : UnsignedIntegerTest/fast

#=============================================================================
# Target rules for targets named UnsignedByte

# Build rule for target.
UnsignedByte: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UnsignedByte
.PHONY : UnsignedByte

# fast build rule for target.
UnsignedByte/fast:
	$(MAKE) -f bin/test/CMakeFiles/UnsignedByte.dir/build.make bin/test/CMakeFiles/UnsignedByte.dir/build
.PHONY : UnsignedByte/fast

#=============================================================================
# Target rules for targets named UnsignedLong

# Build rule for target.
UnsignedLong: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UnsignedLong
.PHONY : UnsignedLong

# fast build rule for target.
UnsignedLong/fast:
	$(MAKE) -f bin/test/CMakeFiles/UnsignedLong.dir/build.make bin/test/CMakeFiles/UnsignedLong.dir/build
.PHONY : UnsignedLong/fast

#=============================================================================
# Target rules for targets named UnsignedShortTest

# Build rule for target.
UnsignedShortTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UnsignedShortTest
.PHONY : UnsignedShortTest

# fast build rule for target.
UnsignedShortTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/UnsignedShortTest.dir/build.make bin/test/CMakeFiles/UnsignedShortTest.dir/build
.PHONY : UnsignedShortTest/fast

src/Boolean.o: src/Boolean.cpp.o

.PHONY : src/Boolean.o

# target to build an object file
src/Boolean.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Boolean.cpp.o
.PHONY : src/Boolean.cpp.o

src/Boolean.i: src/Boolean.cpp.i

.PHONY : src/Boolean.i

# target to preprocess a source file
src/Boolean.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Boolean.cpp.i
.PHONY : src/Boolean.cpp.i

src/Boolean.s: src/Boolean.cpp.s

.PHONY : src/Boolean.s

# target to generate assembly for a file
src/Boolean.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Boolean.cpp.s
.PHONY : src/Boolean.cpp.s

src/Byte.o: src/Byte.cpp.o

.PHONY : src/Byte.o

# target to build an object file
src/Byte.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Byte.cpp.o
.PHONY : src/Byte.cpp.o

src/Byte.i: src/Byte.cpp.i

.PHONY : src/Byte.i

# target to preprocess a source file
src/Byte.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Byte.cpp.i
.PHONY : src/Byte.cpp.i

src/Byte.s: src/Byte.cpp.s

.PHONY : src/Byte.s

# target to generate assembly for a file
src/Byte.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Byte.cpp.s
.PHONY : src/Byte.cpp.s

src/Double.o: src/Double.cpp.o

.PHONY : src/Double.o

# target to build an object file
src/Double.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Double.cpp.o
.PHONY : src/Double.cpp.o

src/Double.i: src/Double.cpp.i

.PHONY : src/Double.i

# target to preprocess a source file
src/Double.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Double.cpp.i
.PHONY : src/Double.cpp.i

src/Double.s: src/Double.cpp.s

.PHONY : src/Double.s

# target to generate assembly for a file
src/Double.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Double.cpp.s
.PHONY : src/Double.cpp.s

src/Float.o: src/Float.cpp.o

.PHONY : src/Float.o

# target to build an object file
src/Float.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Float.cpp.o
.PHONY : src/Float.cpp.o

src/Float.i: src/Float.cpp.i

.PHONY : src/Float.i

# target to preprocess a source file
src/Float.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Float.cpp.i
.PHONY : src/Float.cpp.i

src/Float.s: src/Float.cpp.s

.PHONY : src/Float.s

# target to generate assembly for a file
src/Float.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Float.cpp.s
.PHONY : src/Float.cpp.s

src/Integer.o: src/Integer.cpp.o

.PHONY : src/Integer.o

# target to build an object file
src/Integer.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Integer.cpp.o
.PHONY : src/Integer.cpp.o

src/Integer.i: src/Integer.cpp.i

.PHONY : src/Integer.i

# target to preprocess a source file
src/Integer.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Integer.cpp.i
.PHONY : src/Integer.cpp.i

src/Integer.s: src/Integer.cpp.s

.PHONY : src/Integer.s

# target to generate assembly for a file
src/Integer.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Integer.cpp.s
.PHONY : src/Integer.cpp.s

src/Long.o: src/Long.cpp.o

.PHONY : src/Long.o

# target to build an object file
src/Long.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Long.cpp.o
.PHONY : src/Long.cpp.o

src/Long.i: src/Long.cpp.i

.PHONY : src/Long.i

# target to preprocess a source file
src/Long.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Long.cpp.i
.PHONY : src/Long.cpp.i

src/Long.s: src/Long.cpp.s

.PHONY : src/Long.s

# target to generate assembly for a file
src/Long.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Long.cpp.s
.PHONY : src/Long.cpp.s

src/Object.o: src/Object.cpp.o

.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i

.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s

.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/Short.o: src/Short.cpp.o

.PHONY : src/Short.o

# target to build an object file
src/Short.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Short.cpp.o
.PHONY : src/Short.cpp.o

src/Short.i: src/Short.cpp.i

.PHONY : src/Short.i

# target to preprocess a source file
src/Short.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Short.cpp.i
.PHONY : src/Short.cpp.i

src/Short.s: src/Short.cpp.s

.PHONY : src/Short.s

# target to generate assembly for a file
src/Short.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Short.cpp.s
.PHONY : src/Short.cpp.s

src/String.o: src/String.cpp.o

.PHONY : src/String.o

# target to build an object file
src/String.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/String.cpp.o
.PHONY : src/String.cpp.o

src/String.i: src/String.cpp.i

.PHONY : src/String.i

# target to preprocess a source file
src/String.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/String.cpp.i
.PHONY : src/String.cpp.i

src/String.s: src/String.cpp.s

.PHONY : src/String.s

# target to generate assembly for a file
src/String.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/String.cpp.s
.PHONY : src/String.cpp.s

src/TypeOpUtils.o: src/TypeOpUtils.cpp.o

.PHONY : src/TypeOpUtils.o

# target to build an object file
src/TypeOpUtils.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/TypeOpUtils.cpp.o
.PHONY : src/TypeOpUtils.cpp.o

src/TypeOpUtils.i: src/TypeOpUtils.cpp.i

.PHONY : src/TypeOpUtils.i

# target to preprocess a source file
src/TypeOpUtils.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/TypeOpUtils.cpp.i
.PHONY : src/TypeOpUtils.cpp.i

src/TypeOpUtils.s: src/TypeOpUtils.cpp.s

.PHONY : src/TypeOpUtils.s

# target to generate assembly for a file
src/TypeOpUtils.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/TypeOpUtils.cpp.s
.PHONY : src/TypeOpUtils.cpp.s

src/UnsignedByte.o: src/UnsignedByte.cpp.o

.PHONY : src/UnsignedByte.o

# target to build an object file
src/UnsignedByte.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedByte.cpp.o
.PHONY : src/UnsignedByte.cpp.o

src/UnsignedByte.i: src/UnsignedByte.cpp.i

.PHONY : src/UnsignedByte.i

# target to preprocess a source file
src/UnsignedByte.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedByte.cpp.i
.PHONY : src/UnsignedByte.cpp.i

src/UnsignedByte.s: src/UnsignedByte.cpp.s

.PHONY : src/UnsignedByte.s

# target to generate assembly for a file
src/UnsignedByte.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedByte.cpp.s
.PHONY : src/UnsignedByte.cpp.s

src/UnsignedInteger.o: src/UnsignedInteger.cpp.o

.PHONY : src/UnsignedInteger.o

# target to build an object file
src/UnsignedInteger.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedInteger.cpp.o
.PHONY : src/UnsignedInteger.cpp.o

src/UnsignedInteger.i: src/UnsignedInteger.cpp.i

.PHONY : src/UnsignedInteger.i

# target to preprocess a source file
src/UnsignedInteger.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedInteger.cpp.i
.PHONY : src/UnsignedInteger.cpp.i

src/UnsignedInteger.s: src/UnsignedInteger.cpp.s

.PHONY : src/UnsignedInteger.s

# target to generate assembly for a file
src/UnsignedInteger.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedInteger.cpp.s
.PHONY : src/UnsignedInteger.cpp.s

src/UnsignedLong.o: src/UnsignedLong.cpp.o

.PHONY : src/UnsignedLong.o

# target to build an object file
src/UnsignedLong.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedLong.cpp.o
.PHONY : src/UnsignedLong.cpp.o

src/UnsignedLong.i: src/UnsignedLong.cpp.i

.PHONY : src/UnsignedLong.i

# target to preprocess a source file
src/UnsignedLong.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedLong.cpp.i
.PHONY : src/UnsignedLong.cpp.i

src/UnsignedLong.s: src/UnsignedLong.cpp.s

.PHONY : src/UnsignedLong.s

# target to generate assembly for a file
src/UnsignedLong.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedLong.cpp.s
.PHONY : src/UnsignedLong.cpp.s

src/UnsignedShort.o: src/UnsignedShort.cpp.o

.PHONY : src/UnsignedShort.o

# target to build an object file
src/UnsignedShort.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedShort.cpp.o
.PHONY : src/UnsignedShort.cpp.o

src/UnsignedShort.i: src/UnsignedShort.cpp.i

.PHONY : src/UnsignedShort.i

# target to preprocess a source file
src/UnsignedShort.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedShort.cpp.i
.PHONY : src/UnsignedShort.cpp.i

src/UnsignedShort.s: src/UnsignedShort.cpp.s

.PHONY : src/UnsignedShort.s

# target to generate assembly for a file
src/UnsignedShort.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/UnsignedShort.cpp.s
.PHONY : src/UnsignedShort.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... check"
	@echo "... SRCLIB"
	@echo "... delete"
	@echo "... document"
	@echo "... cmake"
	@echo "... test"
	@echo "... IntegerTest"
	@echo "... FloatTest"
	@echo "... UnsignedIntegerTest"
	@echo "... UnsignedByte"
	@echo "... UnsignedLong"
	@echo "... UnsignedShortTest"
	@echo "... src/Boolean.o"
	@echo "... src/Boolean.i"
	@echo "... src/Boolean.s"
	@echo "... src/Byte.o"
	@echo "... src/Byte.i"
	@echo "... src/Byte.s"
	@echo "... src/Double.o"
	@echo "... src/Double.i"
	@echo "... src/Double.s"
	@echo "... src/Float.o"
	@echo "... src/Float.i"
	@echo "... src/Float.s"
	@echo "... src/Integer.o"
	@echo "... src/Integer.i"
	@echo "... src/Integer.s"
	@echo "... src/Long.o"
	@echo "... src/Long.i"
	@echo "... src/Long.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/Short.o"
	@echo "... src/Short.i"
	@echo "... src/Short.s"
	@echo "... src/String.o"
	@echo "... src/String.i"
	@echo "... src/String.s"
	@echo "... src/TypeOpUtils.o"
	@echo "... src/TypeOpUtils.i"
	@echo "... src/TypeOpUtils.s"
	@echo "... src/UnsignedByte.o"
	@echo "... src/UnsignedByte.i"
	@echo "... src/UnsignedByte.s"
	@echo "... src/UnsignedInteger.o"
	@echo "... src/UnsignedInteger.i"
	@echo "... src/UnsignedInteger.s"
	@echo "... src/UnsignedLong.o"
	@echo "... src/UnsignedLong.i"
	@echo "... src/UnsignedLong.s"
	@echo "... src/UnsignedShort.o"
	@echo "... src/UnsignedShort.i"
	@echo "... src/UnsignedShort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

